### ISSUE TITLE
Dude, where's my unit tests?

### ISSUE THREAD

**Issue by engelsanchez** [basho/riak_ensemble#23]
This repo has no unit tests except for sc.erl, which is disabled in the code.  Did I miss anything? Can we add some?

**Comment by andrewjstone** [comment]
I have the ensemble only test on a branch, but haven't opened a pr yet. I was waiting for the pending data loss pr to merge first which also has another unit test. I agree though, the more tests the better.

**Comment by reiddraper** [comment]
I was under the impression there were EQC/PULSE tests. Do they live somewhere else?

**Comment by reiddraper** [comment]
Adding 2.0 milestone. Let's get these tests running on `develop` before we release 2.0, if at all possible.

**Comment by jtuple** [comment]
`riak_ensemble` is predominately tested via `riak_tests`. Current tests include: `ensemble_basic` through `ensemble_basic4`, `ensemble_interleave`, `ensemble_remove_node` and `ensemble_remove_node2`, and `ensemble_sync`. These tests all live in [riak_test](http://github.com/basho/riak_test).

The aforementioned `sc.erl` test is an EQC test, but it's currently disabled because it requires a cluster of nodes to first be setup by hand before running. There are plans to convert this to an EQC-based `riak_test` to remove the manual configuration. This test can run in both multiple node configuration and single node configuration -- the single-node was the basis for initial PULSE work. So, it would be possible to refactor the test so that it can run in single-node `eunit` form as well as multiple node `riak_test` form. That's been the plan, just need to find the time.

There is very little that is interesting in `riak_ensemble` for which `eunit` style tests makes sense. Sure, there are plans to add them, and we should but they're not critical.

Even the eunit tests Andrew mentioned above are similar to `riak_test` style tests, with the eunit tests launching multiple Erlang nodes, starting/stopping nodes, etc.

There are some eunit tests I want to get in place though. For example, [here's](https://gist.github.com/jtuple/df9c9b253a16e9d47f61) a random manual test that was used months back that could be updated into eunit form -- the reason it wasn't is that I was still fleshing out variation that runs under PULSE/Concuerror. There's still some work to make PULSE/Concuerror work w/ `riak_ensemble` -- we need to change the underlying algorithm a bit to have a mode that doesn't use periodic timers which confuses PULSE/Concuerror to no end.

IMO, the biggest bang-for-buck right now isn't in eunit tests but in simplifying/automating `riak_test` usage.

What I would love to do if we have the time is to make it easy to run `riak_tests` from within top-level `riak_ensemble` as a fully self-contained, zero-config operation. Eg. using either the `rebar riak_test` plugin, an approach similar to Yokozuna's [tools/verify.sh](https://github.com/basho/yokozuna/blob/develop/tools/verify.sh), or something else entirely.

Then, we can extend `make test` for `riak_ensemble` to run the various `riak_test` based tests as the primary CI mechanism.

**Comment by reiddraper** [comment]
Cool. Thanks @jtuple, that helps a lot. I'm +1 on moving this toward 2.1 then. @engelsanchez?

**Comment by engelsanchez** [comment]
Well, some in repo tests are coming, so closing this reminder.
