### ISSUE TITLE
Why does exchange process sync only "PeerMerkleTree",but does't sync data in ensemble backend? [JIRA: RIAK-1786]

### ISSUE THREAD

**Issue by dreyk** [basho/riak_ensemble#65]
Exchange process (riak_ensemble_exchange:exchange) synchronise peers MerkleTree (it insert lost keys to Tree) for ensemble but does't insert lost data in user backend. Is it normal behaviour?

**Comment by nickelization** [comment]
Hi @dreyk, yes, this is the expected behavior. The peer trees allow us to check for corruption, but repairs on the data itself are only done when a client reads or modifies a given key.

It is possible to build asynchronous active repair services on top of riak_ensemble. For instance, Riak the database includes active anti-entropy functionality, which can be applied to strongly consistent buckets to achieve this.

It would be a cool feature if riak_ensemble had some sort of active repair mechanism built in, but it would probably require a substantial amount of work to implement. The best way to do this might be to have repairing peers notify the current leader about corrupted keys, so that the leader could then turn around and trigger read repairs on the corresponding data. I don't know of any current plans at Basho to implement something like this, but if you're interested in taking a stab at it yourself, I'd be happy to chat with you some more on any ideas or plans you might have.

**Comment by dreyk** [comment]
Ok thank you. We have resolved this issue by read-repiar all values after some timeout. In our case amount of data not vary large.
