### ISSUE TITLE
May be add callback to notify user backend module about peer state? [JIRA: RIAK-1794]

### ISSUE THREAD

**Issue by dreyk** [basho/riak_ensemble#67]
I think It will be useful if you can add callback to notify risk_ensemble_backend about peer state changes. I can do PR if accept this proposal.

**Comment by nickelization** [comment]
Hi @dreyk, thanks for posting! Could you elaborate on what sort of use case you would have in mind for this enhancement? The storage backend doesn't normally care what state the peer is in, so I'm curious what sort of functionality would require a callback like that. If we can establish a good use case then I'd love to see a PR; I'm just wondering if there might be a better/easier way to do what you're trying to do, without exposing the peer state to riak_ensemble_backend.

Thanks again, by the way. We're always happy to get new people involved in the project, so I'm looking forward to hearing more about your ideas here - Nick

**Comment by dreyk** [comment]
In my case I want use leader process for start some worker process. This process must be singleton on cluster and it's don't perform any operation on storage. I could use leader tick to start/stop my process, but it's required addition process manager to handle timeout.
Other case related to my previous question https://github.com/basho/riak_ensemble/issues/65. Leader backend may be responsible for data synchronisation.
In these cases i want receive peer states changes.

**Comment by nickelization** [comment]
Okay, cool, makes sense. Since most backends don't care about the peer state, I'm wondering if it would be better to add some sort of independent API function so that any process can register for notifications of local leadership changes. This way we can avoid having to add empty callbacks in all the other storage backends that don't care about peer state, and other processes that aren't part of the storage backend can still watch who the current leader is. Does that sound like a reasonable approach for what you're doing?

**Comment by sumerman** [comment]
@nickelization Unlike callbacks, notifications are asynchronous. So notification may become outdated before it was processed. Callbacks on the other hand are executed by peer itself (if my memory serves me well) and always in sync with its state.

**Comment by dreyk** [comment]
For me that approach is enough.
@sumerman Leader will change current state only after it lost quorum. It's mean that always exists some delay(greater than tick timeout) before it step down. In my mind all work that will start after that notification must be asynchronous and can't change backend state (It's allowed only through standard put/delete)

**Comment by nickelization** [comment]
@sumerman Yeah that's a fair point about synchronous vs. asynchronous, but I think in practice most applications should be doable with an async notification. For instance, if I want to have one process per ensemble that's maintaining some data, and I temporarily have two copies running and they both try to update the data at once, well...we're dealing with strong consistency here, so one will succeed and one will fail. It might not be absolutely 100% efficient, but it should be safe, which is probably more important in 99% of cases.

We also don't want to have potentially long-running callbacks blocking a newly elected leader peer, as that will block availability of the whole ensemble.

If it does come down to it, and we really have a need for a synchronous callback, then I suppose we could consider it. But, even then, I'm not sure if I would want to do it through a storage backend callback. Better to have some separate API call where you pass in a callback fun, since this mechanism doesn't necessarily have anything to do with the storage backend at all.

@dreyk Glad to hear that approach will work for you! By odd coincidence, I actually just found a need for this exact sort of leadership notification in a project I'm working on, so I'm going to go ahead and look into implementing this myself today. If I don't finish it by end of day, I'll push my code so far up to a branch so you can take a look (and even finish it yourself if you're in a rush to have it ready or just feel like doing that).

**Comment by nickelization** [comment]
Changes to address this have been merged here: https://github.com/basho/riak_ensemble/pull/68
